#!/bin/bash
# Helper script to guide Remote Config setup
# Note: Remote Config must be configured manually in Firebase Console

echo "📋 Remote Config Setup Guide"
echo "============================"
echo ""
echo "Since Remote Config requires manual setup in Firebase Console,"
echo "follow these steps:"
echo ""
echo "1. Go to Firebase Console > Remote Config:"
echo "   https://console.firebase.google.com/project/vida-travel-vacation-credit/config"
echo ""
echo "2. Add the following parameters (click 'Add parameter' for each):"
echo ""
echo "   Parameter: zero_interest_headline_es"
echo "   Type: String"
echo "   Default: 0% de Interés Garantizado"
echo "   Variant A: Crédito Sin Intereses"
echo "   Variant B: 0% de Interés Garantizado en tu Crédito de Viaje"
echo ""
echo "   Parameter: zero_interest_headline_en"
echo "   Type: String"
echo "   Default: 0% Interest Guaranteed"
echo "   Variant A: Interest-Free Travel Credit"
echo "   Variant B: 0% Interest Guaranteed on Travel Credit"
echo ""
echo "   Parameter: cta_text_es"
echo "   Type: String"
echo "   Default: Pagar mi cuota de inscripción"
echo "   Variant A: Comenzar mi fondo de viaje"
echo ""
echo "   Parameter: cta_text_en"
echo "   Type: String"
echo "   Default: Pay my enrolment fee"
echo "   Variant A: Start My Vacation Fund"
echo ""
echo "   Parameter: hero_background_image"
echo "   Type: String"
echo "   Default: cancun"
echo "   Variant A: puerto-vallarta"
echo "   Variant B: los-cabos"
echo ""
echo "   Parameter: pricing_display_emphasis"
echo "   Type: String"
echo "   Default: total_price"
echo "   Variant A: monthly_payment"
echo ""
echo "   Parameter: default_loan_term"
echo "   Type: Number"
echo "   Default: 6"
echo "   Variant A: 12"
echo "   Variant B: 9"
echo ""
echo "3. After adding all parameters, click 'Publish changes'"
echo ""
echo "4. To set up A/B Testing:"
echo "   - Go to 'Experiments' tab"
echo "   - Click 'Create experiment'"
echo "   - Select parameters to test"
echo "   - Set traffic allocation"
echo "   - Define success metric: enrollment_fee_click"
echo ""
echo "📄 Full details in COMPLETE_DEPLOYMENT_GUIDE.md"


